# Generated by Django 6.0.5 on 2026-05-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_address'),
        ('suppliers', '0009_alter_currencyrate_rate_to_base_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.orderitem')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_stock_reservations', to='suppliers.supplierproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
