# Generated by Django 6.0.5 on 2026-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstockreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('client_refused', 'Client refused'), ('supplier_unavailable', 'Supplier unavailable'), ('delivery_cost', 'Delivery cost'), ('other', 'Other')], max_length=50),
        ),
    ]
