# Generated by Django 6.0.5 on 2026-05-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancellation_comment_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('shipping', 'Shipping')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_paid_by_customer_on_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_provider',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('transport_company', 'Transport company'), ('other', 'Other')], max_length=50),
        ),
    ]
