# Generated by Django 6.0.5 on 2026-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_comment_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_delivery_comment',
            field=models.TextField(blank=True),
        ),
    ]
