# Generated by Django 6.0.5 on 2026-05-28 08:01

import shop_epower.core.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_manager_delivery_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_snapshot',
            field=models.CharField(default=shop_epower.core.currency.get_base_currency, max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency_snapshot',
            field=models.CharField(default=shop_epower.core.currency.get_base_currency, max_length=10),
        ),
    ]
