# Generated by Django 6.0.5 on 2026-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_currency_snapshot_orderitem_currency_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True),
        ),
    ]
