# Generated by Django 6.0.5 on 2026-09-07 11:38

import django.db.models.deletion
import shop_epower.core.currency
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_legalprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('legal', 'Legal')], max_length=20)),
                ('legal_tax_id_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(default=shop_epower.core.currency.get_base_currency, max_length=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('debt_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_account', to='accounts.legalprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('deposit', 'Deposit'), ('debt_increase', 'Debt increase'), ('allocation', 'Allocation'), ('refund', 'Refund'), ('reversal', 'Reversal')], max_length=30)),
                ('available_delta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_delta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('available_balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_snapshot', models.CharField(max_length=10)),
                ('operation_key', models.CharField(max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_account_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.accounttransaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccountStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='finance.customeraccount')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_account_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['user', 'status'], name='fin_acc_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.UniqueConstraint(fields=('user', 'account_type'), name='unique_customer_account_type_per_user'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', Decimal('0.00'))), name='customer_account_available_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('debt_balance__gte', Decimal('0.00'))), name='customer_account_debt_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type', 'legal'), ('legal_profile__isnull', True), _connector='OR'), name='personal_account_without_legal_profile'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type', 'personal'), ('legal_profile__isnull', False), _connector='OR'), name='legal_account_with_legal_profile'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type', 'legal'), ('legal_tax_id_snapshot', ''), _connector='OR'), name='personal_account_without_legal_tax_id_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type', 'personal'), models.Q(('legal_tax_id_snapshot', ''), _negated=True), _connector='OR'), name='legal_account_with_legal_tax_id_snapshot'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account', 'created_at'], name='fin_tx_account_created_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['operation_type'], name='fin_tx_operation_type_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['actor_type'], name='fin_tx_actor_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance_after__gte', Decimal('0.00'))), name='account_transaction_available_balance_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('debt_balance_after__gte', Decimal('0.00'))), name='account_transaction_debt_balance_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='accounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('available_delta', Decimal('0.00')), ('debt_delta', Decimal('0.00')), _negated=True), name='account_transaction_nonzero_delta'),
        ),
        migrations.AddIndex(
            model_name='customeraccountstatushistory',
            index=models.Index(fields=['account', 'created_at'], name='fin_status_acct_created_idx'),
        ),
    ]
