# Generated by Django 6.0.5 on 2026-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('manager', 'Manager'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
