# Generated by Django 6.0.5 on 2026-05-18 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'ordering': ['id'], 'verbose_name': 'Price category', 'verbose_name_plural': 'Price categories'},
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.pricecategory'),
        ),
    ]
