# Generated by Django 6.0.5 on 2026-05-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pricecategory_options_pricecategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('legal_entity', 'Legal entity'), ('individual_entrepreneur', 'Individual entrepreneur')], max_length=30)),
                ('company_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=20, verbose_name='INN')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='OGRN / OGRNIP')),
                ('legal_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal profile',
                'verbose_name_plural': 'Legal profiles',
            },
        ),
    ]
