# Generated by Django 6.0.5 on 2026-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_legalprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalprofile',
            options={'verbose_name': 'Юридическое лицо / ИП', 'verbose_name_plural': 'Юридические лица / ИП'},
        ),
        migrations.RemoveField(
            model_name='legalprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='legalprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='legalprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='legalprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='legalprofile',
            name='is_legal_entity',
            field=models.BooleanField(default=False, verbose_name='Я представляю юрлицо / ИП'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название организации / ИП'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='УНП / ИНН'),
        ),
    ]
