# Generated by Django 6.0.5 on 2026-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_legalprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalprofile',
            options={'verbose_name': 'Legal profile', 'verbose_name_plural': 'Legal profiles'},
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='is_legal_entity',
            field=models.BooleanField(default=False, verbose_name='Represents a legal entity / sole proprietor'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Legal address'),
        ),
        migrations.AlterField(
            model_name='legalprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tax ID (UNP / INN)'),
        ),
    ]
