# Generated by Django 6.0.5 on 2026-06-11 09:50

import django.db.models.deletion
import shop_epower.core.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_order_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('on_receipt', 'On receipt'), ('invoice', 'By invoice'), ('online', 'Online payment')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('mock', 'Mock provider')], default='manual', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_snapshot', models.CharField(default=shop_epower.core.currency.get_base_currency, max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255)),
                ('manager_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
