# Generated by Django 6.0.5 on 2026-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=100)),
                ('legal_address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=255)),
                ('bank_code', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company settings',
                'verbose_name_plural': 'Company settings',
            },
        ),
    ]
