# Generated by Django 6.0.5 on 2026-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='actual_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='short_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='state_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tax_registration_reason_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
