# Generated by Django 6.0.5 on 2026-06-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_order_comment'),
        ('payments', '0004_companysettings_actual_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('seller_company_name', models.CharField(max_length=255)),
                ('seller_short_company_name', models.CharField(blank=True, max_length=255)),
                ('seller_tax_id', models.CharField(max_length=100)),
                ('seller_tax_registration_reason_code', models.CharField(blank=True, max_length=100)),
                ('seller_state_registration_number', models.CharField(blank=True, max_length=100)),
                ('seller_legal_address', models.TextField()),
                ('seller_actual_address', models.TextField(blank=True)),
                ('seller_bank_name', models.CharField(max_length=255)),
                ('seller_bank_account', models.CharField(max_length=255)),
                ('seller_bank_code', models.CharField(blank=True, max_length=100)),
                ('seller_correspondent_account', models.CharField(blank=True, max_length=255)),
                ('seller_phone', models.CharField(blank=True, max_length=100)),
                ('seller_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=100)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_is_legal_entity', models.BooleanField(default=False)),
                ('buyer_company_name', models.CharField(blank=True, max_length=255)),
                ('buyer_tax_id', models.CharField(blank=True, max_length=100)),
                ('buyer_legal_address', models.TextField(blank=True)),
                ('buyer_bank_name', models.CharField(blank=True, max_length=255)),
                ('buyer_bank_account', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_snapshot', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
