# Generated by Django 6.0.5 on 2026-05-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_own',
            field=models.BooleanField(default=False),
        ),
    ]
