# Generated by Django 6.0.5 on 2026-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_globalmarkup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'ordering': ['supplier', 'product'], 'verbose_name': 'Supplier Product', 'verbose_name_plural': 'Supplier Products'},
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(default='BYN', max_length=3),
        ),
    ]
