# Generated by Django 6.0.5 on 2026-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], max_length=3, unique=True),
        ),
    ]
