# Generated by Django 6.0.5 on 2026-05-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_base_price'),
        ('suppliers', '0006_alter_currencyrate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate_to_BYN',
            field=models.DecimalField(decimal_places=6, help_text='Введите курс так: 1 единица выбранной валюты = X BYN. Например: 1 RUB = 0.038700 BYN, 1 USD = 3.250000 BYN.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('RUB', 'RUB'), ('USD', 'USD')], default='BYN', max_length=3),
        ),
        migrations.CreateModel(
            name='CategoryMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, help_text='Markup percent for this category.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='markup', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category Markup',
                'verbose_name_plural': 'Category Markups',
            },
        ),
    ]
