# Generated by Django 6.0.5 on 2026-05-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_currencyrate_currency_and_more'),
    ]

    operations = [
    migrations.RenameField(
        model_name='currencyrate',
        old_name='rate_to_BYN',
        new_name='rate_to_base_currency',
    ),
]
