# Generated by Django 6.0.5 on 2026-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_auto_20260525_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate_to_base_currency',
            field=models.DecimalField(decimal_places=6, help_text='Введите курс так: 1 единица выбранной валюты = X базовой валюты проекта. Например: если базовая валюта BYN → 1 RUB = 0.038700 BYN.', max_digits=12),
        ),
    ]
