# Generated by Django 6.0.5 on 2026-05-20 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_productvariant_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='internal_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Internal code'),
        ),
    ]
