# Generated by Django 6.0.5 on 2026-05-26 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('variant_type', models.CharField(default='color', help_text='For example: color, size, version, material.', max_length=50, verbose_name='Variant type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('products', models.ManyToManyField(related_name='variant_groups', to='catalog.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Product variant group',
                'verbose_name_plural': 'Product variant groups',
            },
        ),
    ]
