# Generated by Django 6.0.5 on 2026-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariantgroup'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='catalog_pro_product_460665_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='catalog_pro_color_d3de6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='catalog_pro_interna_ab29e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='catalog_pro_is_acti_ce92a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='catalog_pro_variant_7ad435_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
